# Data Cleaning Process

### Pedro Antonio Ramonetti
### UCID: 12324731

For this project, I'm using data that was collected by the National Institute of Statistics and Geography  of Mexico, to understand the impact of COVID-19 on Mexican Education.

The files that are going to be cleaned are the following (both can be found in the raw data folder):

* TMODULO.csv: This file captures the surveys that were individually collected for each student in the sample. Most of these surveys were answered by a relative who was found to be in the house at the moment of the survey.
* TVIVIENDA.csv: This file captures the surveys collected at household level.

## Household Data Cleaning

In [1]:
import pandas as pd
import numpy as np

# First, I read the data.

df_household = pd.read_csv("raw_data/TVIVIENDA.csv", low_memory = False)

# Drop variables that are not gonna be used. These variables counts the members of the household (not useful for us).

df_household.drop(df_household.iloc[:, 1:29], inplace=True, axis=1)

In [2]:
# Rename column to identify them more easily. The question ask if the household has the following goods

df_household.rename(columns = {'P2_1_1':"P2_desktop", 'P2_1_2':"P2_laptop", 'P2_1_3':"P2_tv", 
                     'P2_1_4':"P2_tablet", 'P2_1_5':"P2_smartphone", 'P2_1_6':"P2_internet"}, inplace = True)

# I dont't have use for the following variables:
df_household.drop(df_household.iloc[:, 7:15], inplace=True, axis=1)
df_household

,ENT,P2_desktop,P2_laptop,P2_tv,P2_tablet,P2_smartphone,P2_internet,P4_1_8,P4_2_1,P4_2_2,...,P4_3_1,P4_3_2,P4_3_3,P4_3_4,P4_3_5,P4_3_6,P4_3_7,P4_3_8,P4_3_9,FACTOR
0,1,2.0,1.0,1.0,2.0,1.0,2.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1374
1,1,2.0,1.0,1.0,1.0,1.0,1.0,2.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,887
2,1,2.0,1.0,1.0,1.0,1.0,1.0,2.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1450
3,1,2.0,1.0,1.0,2.0,1.0,1.0,2.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,941
4,1,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1303
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5467,32,2.0,2.0,2.0,2.0,1.0,1.0,2.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1659
5468,32,2.0,2.0,2.0,2.0,1.0,2.0,2.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2403
5469,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3857
5470,32,2.0,2.0,1.0,2.0,1.0,2.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1716
5471,32,2.0,1.0,1.0,2.0,1.0,1.0,2.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1154

In [3]:
# I'm saving the following columns in a different df, since the number of missing values is different. These 
# questions have to do with the advantages and disavantages of remote classes. Not really sure if I'm using them

df_household_2 = df_household.drop(columns=["P2_desktop","P2_laptop", "P2_tv", "P2_tablet", "P2_smartphone", "P2_internet"])

# Now I drop them from the original df
df_household.drop(df_household.iloc[:, 7:27], inplace=True, axis=1)

#Drop NA's
df_household = df_household.dropna()
df_household

,ENT,P2_desktop,P2_laptop,P2_tv,P2_tablet,P2_smartphone,P2_internet,FACTOR
0,1,2.0,1.0,1.0,2.0,1.0,2.0,1374
1,1,2.0,1.0,1.0,1.0,1.0,1.0,887
2,1,2.0,1.0,1.0,1.0,1.0,1.0,1450
3,1,2.0,1.0,1.0,2.0,1.0,1.0,941
4,1,2.0,2.0,2.0,2.0,1.0,2.0,1303
...,...,...,...,...,...,...,...,...
5466,32,2.0,2.0,2.0,2.0,1.0,1.0,1923
5467,32,2.0,2.0,2.0,2.0,1.0,1.0,1659
5468,32,2.0,2.0,2.0,2.0,1.0,2.0,2403
5470,32,2.0,2.0,1.0,2.0,1.0,2.0,1716
5471,32,2.0,1.0,1.0,2.0,1.0,1.0,1154

In [4]:
# Make variables into an appropiate dummy format

for (_, colname) in enumerate(df_household):
    if colname=="ENT" or colname=="FACTOR":
        continue
    else:
        df_household.loc[df_household[colname] == 2, colname] = 0
        
df_household

,ENT,P2_desktop,P2_laptop,P2_tv,P2_tablet,P2_smartphone,P2_internet,FACTOR
0,1,0.0,1.0,1.0,0.0,1.0,0.0,1374
1,1,0.0,1.0,1.0,1.0,1.0,1.0,887
2,1,0.0,1.0,1.0,1.0,1.0,1.0,1450
3,1,0.0,1.0,1.0,0.0,1.0,1.0,941
4,1,0.0,0.0,0.0,0.0,1.0,0.0,1303
...,...,...,...,...,...,...,...,...
5466,32,0.0,0.0,0.0,0.0,1.0,1.0,1923
5467,32,0.0,0.0,0.0,0.0,1.0,1.0,1659
5468,32,0.0,0.0,0.0,0.0,1.0,0.0,2403
5470,32,0.0,0.0,1.0,0.0,1.0,0.0,1716
5471,32,0.0,1.0,1.0,0.0,1.0,1.0,1154

In [5]:
# Specify the regions in our data

northwest=[2,3,8,10,25,26]
northeast=[5,19,28]
west=[6,14,16,18]
east=[13,21,29,30]
northcenter=[1,11,22,24,32]
southcenter=[9,15,17]
southeast=[4,23,27,31]
southwest=[7,12,20]

df_household["Region"] = "Northwest"
df_household["Region"] = np.where(df_household['ENT'].isin(northeast),'Northeast', df_household["Region"])
df_household["Region"] = np.where(df_household['ENT'].isin(west),'West', df_household["Region"])
df_household["Region"] = np.where(df_household['ENT'].isin(east),'East', df_household["Region"])
df_household["Region"] = np.where(df_household['ENT'].isin(northcenter),'Northcenter', df_household["Region"])
df_household["Region"] = np.where(df_household['ENT'].isin(southcenter),'Southcenter', df_household["Region"])
df_household["Region"] = np.where(df_household['ENT'].isin(southeast),'Southeast', df_household["Region"])
df_household["Region"] = np.where(df_household['ENT'].isin(southwest),'southwest', df_household["Region"])

df_household_2["Region"] = "Northwest"
df_household_2["Region"] = np.where(df_household_2['ENT'].isin(northeast),'Northeast', df_household_2["Region"])
df_household_2["Region"] = np.where(df_household_2['ENT'].isin(west),'West', df_household_2["Region"])
df_household_2["Region"] = np.where(df_household_2['ENT'].isin(east),'East', df_household_2["Region"])
df_household_2["Region"] = np.where(df_household_2['ENT'].isin(northcenter),'Northcenter', df_household_2["Region"])
df_household_2["Region"] = np.where(df_household_2['ENT'].isin(southcenter),'Southcenter', df_household_2["Region"])
df_household_2["Region"] = np.where(df_household_2['ENT'].isin(southeast),'Southeast', df_household_2["Region"])
df_household_2["Region"] = np.where(df_household_2['ENT'].isin(southwest),'southwest', df_household_2["Region"])

df_household

C:\Users\pramo\AppData\Local\Temp\ipykernel_23104\2448493461.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_household["Region"] = "Northwest"
C:\Users\pramo\AppData\Local\Temp\ipykernel_23104\2448493461.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_household["Region"] = np.where(df_household['ENT'].isin(northeast),'Northeast', df_household["Region"])
C:\Users\pramo\AppData\Local\Temp\ipykernel_23104\2448493461.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_household["Region"] = np.where(df_household['ENT'].isin(west),'West', df_household["Region"])
C:\Users\pramo\AppData\Local\Temp\ipykernel_23104\2448493461.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_household["Region"] = np.where(df_household['ENT'].isin(east),'East', df_household["Region"])
C:\Users\pramo\AppData\Local\Temp\ipykernel_23104\2448493461.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_household["Region"] = np.where(df_household['ENT'].isin(northcenter),'Northcenter', df_household["Region"])
C:\Users\pramo\AppData\Local\Temp\ipykernel_23104\2448493461.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_household["Region"] = np.where(df_household['ENT'].isin(southcenter),'Southcenter', df_household["Region"])
C:\Users\pramo\AppData\Local\Temp\ipykernel_23104\2448493461.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_household["Region"] = np.where(df_household['ENT'].isin(southeast),'Southeast', df_household["Region"])
C:\Users\pramo\AppData\Local\Temp\ipykernel_23104\2448493461.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_household["Region"] = np.where(df_household['ENT'].isin(southwest),'southwest', df_household["Region"])

,ENT,P2_desktop,P2_laptop,P2_tv,P2_tablet,P2_smartphone,P2_internet,FACTOR,Region
0,1,0.0,1.0,1.0,0.0,1.0,0.0,1374,Northcenter
1,1,0.0,1.0,1.0,1.0,1.0,1.0,887,Northcenter
2,1,0.0,1.0,1.0,1.0,1.0,1.0,1450,Northcenter
3,1,0.0,1.0,1.0,0.0,1.0,1.0,941,Northcenter
4,1,0.0,0.0,0.0,0.0,1.0,0.0,1303,Northcenter
...,...,...,...,...,...,...,...,...,...
5466,32,0.0,0.0,0.0,0.0,1.0,1.0,1923,Northcenter
5467,32,0.0,0.0,0.0,0.0,1.0,1.0,1659,Northcenter
5468,32,0.0,0.0,0.0,0.0,1.0,0.0,2403,Northcenter
5470,32,0.0,0.0,1.0,0.0,1.0,0.0,1716,Northcenter
5471,32,0.0,1.0,1.0,0.0,1.0,1.0,1154,Northcenter

In [6]:
# Before saving our dataset, let's weight the answers of the main questions
cols =["P2_desktop","P2_laptop", "P2_tv", "P2_tablet", "P2_smartphone", "P2_internet"]

for col in cols:
    colname = col+"_w"
    df_household[colname] = df_household[col] * df_household["FACTOR"]

# Finally, let's group our main df

df_household = df_household.groupby(["ENT","Region"]).sum()

#We save our df's. As I mentioned, not really sure if using the second one

df_household.to_csv("household_clean.csv", index = True)
df_household_2.to_csv("household_2_clean.csv", index = False)

df_household

C:\Users\pramo\AppData\Local\Temp\ipykernel_23104\4267199039.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_household[colname] = df_household[col] * df_household["FACTOR"]
C:\Users\pramo\AppData\Local\Temp\ipykernel_23104\4267199039.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_household[colname] = df_household[col] * df_household["FACTOR"]
C:\Users\pramo\AppData\Local\Temp\ipykernel_23104\4267199039.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_household[colname] = df_household[col] * df_household["FACTOR"]
C:\Users\pramo\AppData\Local\Temp\ipykernel_23104\4267199039.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_household[colname] = df_household[col] * df_household["FACTOR"]
C:\Users\pramo\AppData\Local\Temp\ipykernel_23104\4267199039.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_household[colname] = df_household[col] * df_household["FACTOR"]
C:\Users\pramo\AppData\Local\Temp\ipykernel_23104\4267199039.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_household[colname] = df_household[col] * df_household["FACTOR"]

,,P2_desktop,P2_laptop,P2_tv,P2_tablet,P2_smartphone,P2_internet,FACTOR,P2_desktop_w,P2_laptop_w,P2_tv_w,P2_tablet_w,P2_smartphone_w,P2_internet_w
ENT,Region,,,,,,,,,,,,,
1,Northcenter,62.0,104.0,172.0,65.0,209.0,167.0,286576,75564.0,128791.0,221224.0,83552.0,269764.0,208761.0
2,Northwest,44.0,74.0,124.0,35.0,136.0,123.0,795151,228622.0,365148.0,665199.0,184284.0,751142.0,638939.0
3,Northwest,22.0,51.0,95.0,25.0,114.0,82.0,193859,33323.0,74882.0,153594.0,40117.0,183034.0,129611.0
4,Southeast,41.0,90.0,137.0,48.0,169.0,118.0,193629,37580.0,91133.0,151139.0,52822.0,185329.0,120971.0
5,Northeast,25.0,67.0,122.0,40.0,147.0,112.0,632127,99420.0,263505.0,487090.0,179613.0,588532.0,450120.0
6,West,25.0,42.0,82.0,25.0,84.0,68.0,164410,38164.0,55036.0,140854.0,39454.0,138607.0,105691.0
7,southwest,20.0,51.0,109.0,27.0,161.0,71.0,975002,89438.0,203730.0,565410.0,123351.0,825559.0,326794.0
8,Northwest,41.0,86.0,144.0,46.0,173.0,133.0,796027,168478.0,347269.0,601272.0,202785.0,735923.0,551136.0
9,Southcenter,46.0,74.0,136.0,39.0,154.0,126.0,1853176,554929.0,859997.0,1534481.0,456706.0,1819890.0,1400469.0
10,Northwest,35.0,75.0,155.0,44.0,175.0,120.0,381980,67485.0,142263.0,307987.0,88298.0,345488.0,230340.0
11,Northcenter,8.0,25.0,41.0,14.0,59.0,40.0,1127052,98491.0,330841.0,653022.0,158277.0,1074026.0,560888.0
12,southwest,21.0,40.0,88.0,14.0,121.0,79.0,742019,80901.0,171028.0,455238.0,74304.0,650058.0,397057.0
13,East,22.0,47.0,72.0,26.0,103.0,73.0,519425,99530.0,193735.0,337350.0,132445.0,483946.0,343234.0
14,West,32.0,51.0,81.0,35.0,114.0,92.0,1684885,404026.0,653739.0,1073256.0,467266.0,1555297.0,1228310.0
15,Southcenter,51.0,69.0,139.0,35.0,162.0,141.0,3487972,1007356.0,1302426.0,2798823.0,728900.0,3303064.0,2824792.0
16,West,30.0,64.0,108.0,34.0,143.0,102.0,919921,133955.0,285161.0,623851.0,162133.0,805877.0,485319.0
17,Southcenter,24.0,71.0,121.0,40.0,162.0,127.0,423812,52122.0,152774.0,291467.0,98054.0,395880.0,298025.0
18,West,29.0,78.0,139.0,51.0,180.0,129.0,282489,36512.0,94644.0,183399.0,64990.0,245641.0,171453.0
19,Northeast,31.0,53.0,97.0,38.0,105.0,92.0,1119820,273061.0,464083.0,916439.0,367164.0,991480.0,865778.0
20,southwest,20.0,46.0,86.0,15.0,123.0,72.0,741610,82060.0,147846.0,428508.0,48507.0,642979.0,304631.0
21,East,34.0,44.0,79.0,28.0,99.0,81.0,1207811,331457.0,389262.0,786140.0,286091.0,949139.0,776799.0
22,Northcenter,39.0,54.0,97.0,27.0,101.0,89.0,411021,139169.0,176651.0,337875.0,90914.0,350386.0,303068.0
23,Southeast,16.0,44.0,78.0,18.0,101.0,75.0,406611,55248.0,143879.0,283943.0,61475.0,369704.0,257956.0
24,Northcenter,23.0,41.0,81.0,26.0,92.0,63.0,569562,75749.0,190413.0,366200.0,141201.0,477541.0,245243.0
25,Northwest,23.0,68.0,111.0,35.0,147.0,95.0,616092,72404.0,246356.0,438269.0,134588.0,594888.0,356263.0
26,Northwest,26.0,58.0,72.0,23.0,99.0,69.0,627523,152475.0,328974.0,430744.0,139425.0,606836.0,418697.0
27,Southeast,16.0,32.0,71.0,18.0,90.0,45.0,514011,86623.0,132777.0,375898.0,76235.0,478698.0,203049.0
28,Northeast,15.0,39.0,93.0,21.0,108.0,73.0,837858,102677.0,240539.0,692513.0,169536.0,808277.0,516562.0
29,East,52.0,100.0,165.0,24.0,224.0,160.0,255171,45212.0,92069.0,171752.0,24729.0,236451.0,158083.0
30,East,24.0,46.0,90.0,25.0,120.0,76.0,1514357,295063.0,579075.0,1081353.0,287883.0,1455586.0,935834.0
31,Southeast,25.0,76.0,131.0,34.0,182.0,117.0,460803,57444.0,183598.0,315200.0,85236.0,445394.0,284917.0
32,Northcenter,41.0,68.0,139.0,31.0,158.0,93.0,342543,67421.0,113255.0,264762.0,53906.0,299829.0,161837.0

## Individuals Data Cleaning

In [7]:
# First, I read the data.

df = pd.read_csv("raw_data/TMODULO.csv", low_memory = False)

In [8]:
# I know I'm not using the following variables.

to_drop = ["P3_22","P3_15","P3_21_1","P3_21_2","P3_21_3","P3_21_5","P3_21_6","P3_21_7","P3_21A","P3_21B","P3_21_4",
           "P3_10","P3_12_12A","P3_5","P3_6","NIV","GRA","CON","N_REN", "PAREN","P3_9_1","P3_9_2","P3_9_3",
           "P3_9_4","P3_9_5","P3_9_6","P3_9_7","P3_9_8","P3_9_9","P3_19_1","P3_19_2","P3_19_3","P3_19_4",
           "P3_19_5","P3_19_6","P3_19_7","P3_19_8"]

for col in to_drop:
    df = df.drop([col], axis=1)

# All of the following columns are dummy variables, that are not correctly codified. We are also gonna weight them
dummies = ["P3_13","P3_5","P3_6","P3_7","P3_8","P3_9_1","P3_9_2","P3_9_3","P3_9_4",
"P3_9_5","P3_9_6","P3_9_7","P3_9_8","P3_9_9","P3_11","P3_12_1",
"P3_12_2","P3_12_3","P3_12_4","P3_12_5","P3_12_6","P3_12_7",
"P3_12_8","P3_14","P3_16","P3_17_1","P3_17_2","P3_17_3","P3_17_4",
"P3_17_5","P3_17_6","P3_17_7","P3_17_8","P3_20","P3_23"]

for dummy in dummies:
    df.loc[df[dummy] == 2, dummy] = 0
    colname = dummy + "_w"
    df[colname] = df[dummy] * df["FACTOR"]

In [9]:
# Specify the regions

df["Region"] = "Northwest"
df["Region"] = np.where(df['ENT'].isin(northeast),'Northeast', df["Region"])
df["Region"] = np.where(df['ENT'].isin(west),'West', df["Region"])
df["Region"] = np.where(df['ENT'].isin(east),'East', df["Region"])
df["Region"] = np.where(df['ENT'].isin(northcenter),'Northcenter', df["Region"])
df["Region"] = np.where(df['ENT'].isin(southcenter),'Southcenter', df["Region"])
df["Region"] = np.where(df['ENT'].isin(southeast),'Southeast', df["Region"])
df["Region"] = np.where(df['ENT'].isin(southwest),'southwest', df["Region"])

In [11]:
# We correct the gender and "Public / Private School" variables
df["gender_string"] = "female"
df["gender_string"] = np.where((df["SEXO"] == 1),'male', df["gender_string"])

df["P3_6_string"] = "public"
df["P3_15_string"] = "public"

df["P3_6_string"] = np.where((df["P3_6"] == 2),'private', df["P3_6_string"])
df["P3_15_string"] = np.where((df["P3_15"] == 2),'private', df["P3_15_string"])

In [12]:
# Save the clean file. I'm uncertain on which exact variables I'm going to use, so I want to preserve the file as it is for now.
df.to_csv("students_clean.csv", index = False)

# Codebook 

## HH level data

* P2_desktop: Does the household counts with a desktop? 
* P2_laptop: ....laptop?
* P2_tv: ....tv? 
* P2_tablet: ....tablet? 
* P2_smartphone: ....smartphone? 
* P2_internet: ....internet?
* FACTOR = Total number of houses
* P2_desktop_w: Does the household counts with a desktop? (weighted) 
* P2_laptop_w: ....laptop? (weighted)
* P2_tv_w: ....tv? (weighted)
* P2_tablet_W: ....tablet? (weighted)
* P2_smartphone_W: ....smartphone? (weighted)
* P2_internet_W: ....internet? (weighted)

## Student Level
* ENT: State
* SEXO: Gender
* EDAD: Age
* P3_7: Did you finish school last year? (1 for yes)
* P3_8: Did you leave school because of covid? (1 for yes)
* P3_11: Did you keep in touch with your professor? (1 for yes)
* P3_12_1: During the pandemic, did you use desktop for your school activies? (1 for yes)
* P3_12_2: ....laptop?
* P3_12_3: ....tablet?
* P3_12_4: ....smartphone?
* P3_12_5: ....tv?
* P3_12_6: ....other?
* P3_12_7: ....none?
* P3_12_8: ....no remote classes?
* P3_14: Are you enrolled in this academic year? (1 for yes)
* P3_16: Are you not currently enrolled because of covid? (1 for yes)
* P3_17_1: How is covid harming you? - I don't have a laptop (1 for yes)
* P3_17_2: .... my parents lost their job
* P3_17_3: .... I got covid
* P3_17_4: .... a family member died of covid
* P3_17_5: .... my school closed
* P3_17_6: .... I need to take care of a family member
* P3_17_7: .... remote classes don't work for me
* P3_17_8: .... other
* P3_18: Main reason why you are not attending school
* P3_20: Do you stay in touch with your professor? (1 for yes)
* P3_23: Does anyone help you with your school activities? (1 for yes)
* P3_24: Who helps you the most with you school activities (mom, dad).
* P3_25_1: How does your school stays in touch with you? - Posters outside of the school (1 for yes)
* P3_25_2: ....social media
* P3_25_3: ....virtual platforms
* P3_25_4: ....phone
* P3_25_5: ....other
* P3_26: How likely is that you return to school next year?
* FACTOR: Weight
* P3_7_w: Did you finish school last year? (weighted)
* P3_8_w: Did you leave school because of covid? (weighted)
* P3_11_w: Did you keep in touch with your professor? (weighted) 
* P3_12_1_w: During the pandemic, did you use desktop for your school activies? (weighted)
* P3_12_2_w: ....laptop?
* P3_12_3_w: ....tablet?
* P3_12_4_w: ....smartphone?
* P3_12_5_w: ....tv?
* P3_12_6_w: ....other?
* P3_12_7_w: ....none?
* P3_12_8_w: ....no remote classes?
* P3_14: Are you enrolled in this academic year? (weighted)
* P3_16_w: Are you not currently enrolled because of covid? (weighted)
* P3_17_1_w: How is covid harming you? - I don't have a laptop (weighted)
* P3_17_2_w: .... my parents lost their job 
* P3_17_3_w: .... I got covid
* P3_17_4_w: .... a family member died of covid
* P3_17_5_w: .... my school closed
* P3_17_6_w: .... I need to take care of a family member
* P3_17_7_w: .... remote classes don't work for me
* P3_17_8_w: .... other
* P3_20_w: Do you stay in touch with your professor? (weighted)
* P3_23_w Does anyone help you with your school activities? (weighted)